### PR TITLE
Migrate to use abbot cli

### PR DESCRIPTION
**Pull request by haacked**
This updates the repository to reflect the structure expected by [`abbot-cli`](https://github.com/aseriousbiz/abbot-cli). The next step is to set up a GitHub action to deploy changes when a skill is changed.

### CODE REVIEW

**Comment by haacked** [comment]
@shana Do you know of any GitHub Action magic kung-fu that would allow us to only deploy skills that have changed?

Here's the basic idea. I want a GitHub action such that when `./{skill}/main.{ext}` is changed, we're able to run `abbot deploy {skill}`.

So if I change `./tz/main.csx`, and merge that change to `main`, we'd run `abbot deploy tz`.

**Comment by haacked** [comment]
Another idea is not put this on GitHub Actions. Instead, I'll add an option to `abbot deploy` where it will deploy all skills that have changed. If we do that, we need to make sure we can commit the updated `.concurrency` file in our GitHub Action.

**Comment by shana** [comment]
Yeah we should be able to calculate which paths have changes and only deploy those skills, I already do regex stuff to parse arguments to github actions and generate dynamic arguments to if statements. I can hack something together in the morning!

**Comment by shana** [comment]
Ok main now has a workflow that will auto-deploy skills that have changed, based on path detection - all paths with a `main.[csx|py|js] ` that have changed since the last commit, and in the case of merges, the "last commit" is the merge.

On pull request updates, it will list the changed files but won't deploy. I'm not sure if it will run on this PR though, because this branch doesn't have the workflow file yet - I don't know if github only runs workflows that exist on a branch, or if they run workflows that exist on the PR merge commit.

The workflow is "pretend" deploying right now, since it doesn't yet have the abbot cli tool to do the actual thing.

**Comment by haacked** [comment]
> I don't know if github only runs workflows that exist on a branch, or if they run workflows that exist on the PR merge commit.

The workflow has to exist in the branch for it to run.

**Pull request merged**
